Repository IntelligenceModding/AdvancedPeripherals, pull requests merged in 2024-06, with the labels that each got.

#622 Backported changes from the CC: Tweaked Gametest framework present in 1.20.x
  build.gradle
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/cc/tweaked/gradle/Extensions.kt
  buildSrc/src/main/kotlin/cc/tweaked/gradle/ForgeExtensions.kt
  buildSrc/src/main/kotlin/cc/tweaked/gradle/MinecraftExec.kt
  buildSrc/src/main/kotlin/cc/tweaked/gradle/ProcessHelpers.kt
  buildSrc/src/main/kotlin/net/minecraftforge/gradle/common/util/runs/RunConfigSetup.kt
  docs/CREATING_TESTS.MD
  src/testMod/java/dan200/computercraft/gametest/core/CCTestCommand.java
  src/testMod/java/dan200/computercraft/gametest/core/ClientHooks.java
  src/testMod/java/dan200/computercraft/gametest/core/MinecraftExtensions.java
  src/testMod/java/dan200/computercraft/gametest/core/TestAPI.java
  src/testMod/java/dan200/computercraft/gametest/core/TestHooks.java
  src/testMod/java/dan200/computercraft/gametest/core/TestMod.java
  src/testMod/java/dan200/computercraft/mixin/gametest/GameTestSequenceMixin.java
  src/testMod/java/dan200/computercraft/mixin/gametest/client/LevelSummaryMixin.java
  src/testMod/java/dan200/computercraft/mixin/gametest/client/MinecraftMixin.java
  src/testMod/java/dan200/computercraft/mixin/gametest/client/WorldOpenFlowsMixin.java
  src/testMod/kotlin/dan200/computercraft/gametest/api/ClientGameTest.kt
  src/testMod/kotlin/dan200/computercraft/gametest/api/ClientTestExtensions.kt
  src/testMod/kotlin/dan200/computercraft/gametest/api/TestExtensions.kt
  src/testMod/kotlin/dan200/computercraft/gametest/api/TestTags.kt
  src/testMod/kotlin/dan200/computercraft/gametest/core/ClientTestHooks.kt
  src/testMod/kotlin/dan200/computercraft/gametest/core/TestHooks.kt
  src/testMod/kotlin/dan200/computercraft/gametest/core/TestReporters.kt
  src/testMod/resources/ccgametest.mixins.json
Labels: 1.19x

#601 Add tamed turtle
  build.gradle
  src/generated/resources/.cache/03e4de26f1265135874f8cdcaebc09d9c08eb42b
  src/generated/resources/.cache/2db41954e490230d51b10affff25ee2ee27b8d5b
  src/generated/resources/.cache/5a761efb7472ef97566e41e81451930a004134bf
  src/generated/resources/.cache/67cce32b1c3cbbcb1f646605f4914e3f196986c2
  src/generated/resources/.cache/9fb1092f32d4fcbf9e061ffd718d4ec689c6c95e
  src/generated/resources/.cache/ae219fa7c7d3297c14e454863eac3998a4eab78c
  src/generated/resources/.cache/b8526e444ae7356037f3a813274f6835d1f3dd16
  src/generated/resources/.cache/c622617f6fabf890a00b9275cd5f643584a8a2c8
  src/generated/resources/.cache/f95c7003282837dabaa33e3ffceec4e6865b5218
  src/generated/resources/assets/advancedperipherals/lang/en_us.json
  src/generated/resources/data/advancedperipherals/computercraft/turtle_upgrades/saddle_turtle.json
  src/main/java/de/srendi/advancedperipherals/APCreativeTab.java
  src/main/java/de/srendi/advancedperipherals/client/ClientEventSubscriber.java
  src/main/java/de/srendi/advancedperipherals/client/ClientRegistry.java
  src/main/java/de/srendi/advancedperipherals/client/screens/SaddleTurtleScreen.java
  src/main/java/de/srendi/advancedperipherals/common/addons/computercraft/operations/SimpleFreeOperation.java
  src/main/java/de/srendi/advancedperipherals/common/addons/computercraft/operations/SingleOperation.java
  src/main/java/de/srendi/advancedperipherals/common/addons/computercraft/operations/SphereOperation.java
  src/main/java/de/srendi/advancedperipherals/common/addons/computercraft/owner/TurtlePeripheralOwner.java
  src/main/java/de/srendi/advancedperipherals/common/addons/computercraft/peripheral/ChunkyPeripheral.java
  src/main/java/de/srendi/advancedperipherals/common/addons/computercraft/peripheral/EnvironmentDetectorPeripheral.java
  src/main/java/de/srendi/advancedperipherals/common/addons/computercraft/peripheral/SaddlePeripheral.java
  src/main/java/de/srendi/advancedperipherals/common/addons/computercraft/peripheral/plugins/AutomataEntityHandPlugin.java
  src/main/java/de/srendi/advancedperipherals/common/addons/computercraft/peripheral/plugins/AutomataEntityTransferPlugin.java
  src/main/java/de/srendi/advancedperipherals/common/addons/computercraft/peripheral/plugins/AutomataLookPlugin.java
  src/main/java/de/srendi/advancedperipherals/common/addons/computercraft/peripheral/plugins/AutomataWarpingPlugin.java
  src/main/java/de/srendi/advancedperipherals/common/addons/computercraft/turtles/TurtleSaddleUpgrade.java
  src/main/java/de/srendi/advancedperipherals/common/configuration/PeripheralsConfig.java
  src/main/java/de/srendi/advancedperipherals/common/data/EnUsLanguageProvider.java
  src/main/java/de/srendi/advancedperipherals/common/data/TurtleUpgradesProvider.java
  src/main/java/de/srendi/advancedperipherals/common/entity/TurtleSeatEntity.java
  src/main/java/de/srendi/advancedperipherals/common/network/PacketHandler.java
  src/main/java/de/srendi/advancedperipherals/common/network/toclient/SaddleTurtleInfoPacket.java
  src/main/java/de/srendi/advancedperipherals/common/network/toserver/SaddleTurtleControlPacket.java
  src/main/java/de/srendi/advancedperipherals/common/setup/APEntities.java
  src/main/java/de/srendi/advancedperipherals/common/setup/CCRegistration.java
  src/main/java/de/srendi/advancedperipherals/common/util/EnumColor.java
  src/main/java/de/srendi/advancedperipherals/common/util/LuaConverter.java
  src/main/java/de/srendi/advancedperipherals/common/util/fakeplayer/FakePlayerProviderTurtle.java
Labels: enhancement, 1.19x, 1.20x

#631 fix #620 Modules only apply after closing and re-opening the glasses inventory
  build.gradle
  src/main/java/de/srendi/advancedperipherals/common/container/SmartGlassesContainer.java
  src/main/java/de/srendi/advancedperipherals/common/items/SmartGlassesItem.java
  src/main/java/de/srendi/advancedperipherals/common/smartglasses/SmartGlassesComputer.java
  src/main/java/de/srendi/advancedperipherals/common/smartglasses/SmartGlassesItemHandler.java
  src/main/java/de/srendi/advancedperipherals/common/smartglasses/SmartGlassesSlot.java
  src/main/java/de/srendi/advancedperipherals/common/smartglasses/modules/ModulePeripheral.java
  src/main/java/de/srendi/advancedperipherals/common/smartglasses/modules/nightvision/NightVisionFunctions.java
  src/main/java/de/srendi/advancedperipherals/common/smartglasses/modules/nightvision/NightVisionModule.java
  src/main/java/de/srendi/advancedperipherals/common/smartglasses/modules/nightvision/NightVisionModuleItem.java
Labels: bug, 1.19x

#619 Add chatbox message filter
  src/main/java/de/srendi/advancedperipherals/common/addons/computercraft/peripheral/ChatBoxPeripheral.java
  src/main/java/de/srendi/advancedperipherals/common/commands/APCommands.java
  src/main/java/de/srendi/advancedperipherals/common/configuration/PeripheralsConfig.java
Labels: 1.19x

#638 Add wandering trader config
  src/main/java/de/srendi/advancedperipherals/common/configuration/WorldConfig.java
  src/main/java/de/srendi/advancedperipherals/common/village/VillagerTrades.java
Labels: enhancement, 1.19x
