Repository IntelligenceModding/AdvancedPeripherals, pull requests merged in 2024-07, with the labels that each got.

#628 Added client test for the Chat Box peripheral
  build.gradle
  buildSrc/src/main/kotlin/cc/tweaked/gradle/MinecraftExec.kt
  src/testMod/java/dan200/computercraft/gametest/core/ClientTestEvents.java
  src/testMod/kotlin/dan200/computercraft/gametest/core/ClientTestHooks.kt
  src/testMod/kotlin/de/srendi/advancedperipherals/test/APClientTestExtensions.kt
  src/testMod/kotlin/de/srendi/advancedperipherals/test/ChatBoxTest.kt
  src/testMod/kotlin/de/srendi/advancedperipherals/test/ComponentFormattedCharSink.kt
  src/testMod/resources/META-INF/accesstransformer.cfg
  src/testMod/resources/data/advancedperipheralstest/computer/tests/chatboxtest.chatbox.lua
  src/testMod/resources/data/advancedperipheralstest/computer/tests/chatboxtest.chatbox_events.lua
  src/testMod/resources/data/advancedperipheralstest/structures/chatboxtest.chatbox.snbt
  src/testMod/resources/data/advancedperipheralstest/structures/chatboxtest.chatbox_events.snbt
Labels: 1.19x

#641 Fix Peripheral throws NullPointerException when invoking getName method
  src/main/java/de/srendi/advancedperipherals/common/addons/computercraft/owner/BlockEntityPeripheralOwner.java
Labels: bug, 1.20x

#644 fix useOnBlock will returns PASS on some specific case
  src/main/java/de/srendi/advancedperipherals/common/util/fakeplayer/APFakePlayer.java
Labels: 1.19x, 1.20x

#643 rename getEnergy -> getStoredEnergy
  src/main/java/de/srendi/advancedperipherals/common/addons/computercraft/owner/BlockEntityPeripheralOwner.java
  src/main/java/de/srendi/advancedperipherals/common/addons/powah/EnderCellIntegration.java
  src/main/java/de/srendi/advancedperipherals/common/addons/powah/EnergyCellIntegration.java
  src/main/java/de/srendi/advancedperipherals/common/addons/powah/FurnatorIntegration.java
  src/main/java/de/srendi/advancedperipherals/common/addons/powah/MagmatorIntegration.java
  src/main/java/de/srendi/advancedperipherals/common/addons/powah/ReactorIntegration.java
  src/main/java/de/srendi/advancedperipherals/common/addons/powah/SolarPanelIntegration.java
  src/main/java/de/srendi/advancedperipherals/common/addons/powah/ThermoIntegration.java
Labels: 1.20x
